name: slack-notification

on:  [ push, pull_request  ]
jobs:
  slack-notifications:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-text: Hello! Event to "${{ github.event_name }}" in "${{ github.repository }}" ðŸ¤“
      
